name: Friendly Skies
favicon: null
layout_spectrum: 1
typography_spectrum: 0.31586
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d31111'
    - '#214b9f'
    - '#acbbdb'
    - '#db4243'
  brandStrength: 0.3125
  lightness: 0.8125
  saturation: 0.625
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    item: null
    url: null
