name: Friendly Skies
favicon: null
layout_spectrum: 1
typography_spectrum: 0.31083
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d31111'
    - '#224ca0'
    - '#ff0000'
    - '#800000'
    - '#000000'
  brandStrength: 0.3125
  lightness: 0.8125
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    item: null
    url: null
